"""添加评论举报数字段

Revision ID: 4d939fb5fc65
Revises: 8cad6c4f8958
Create Date: 2018-12-20 19:10:14.979232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d939fb5fc65'
down_revision = '8cad6c4f8958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('flag', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'flag')
    # ### end Alembic commands ###
