"""添加用户在线记录模型

Revision ID: 790217a22eba
Revises: 4d939fb5fc65
Create Date: 2018-12-22 19:06:38.259157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790217a22eba'
down_revision = '4d939fb5fc65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useronline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('lasttime', sa.DateTime(), nullable=True),
    sa.Column('clike', sa.SmallInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_useronline_lasttime'), 'useronline', ['lasttime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_useronline_lasttime'), table_name='useronline')
    op.drop_table('useronline')
    # ### end Alembic commands ###
