"""添加type_photo字段

Revision ID: 8cad6c4f8958
Revises: 
Create Date: 2018-12-19 16:58:01.734528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cad6c4f8958'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('type_photo', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'type_photo')
    # ### end Alembic commands ###
